// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// red_execute.cpp
cpp11::writable::list redatam_internal_query(SEXP dic, const std::string& spc);
extern "C" SEXP _censo2022arg_redatam_internal_query(SEXP dic, SEXP spc) {
  BEGIN_CPP11
    return cpp11::as_sexp(redatam_internal_query(cpp11::as_cpp<cpp11::decay_t<SEXP>>(dic), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(spc)));
  END_CPP11
}
// red_execute.cpp
cpp11::writable::list redatam_internal_run(SEXP dic, const std::string& file_name);
extern "C" SEXP _censo2022arg_redatam_internal_run(SEXP dic, SEXP file_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(redatam_internal_run(cpp11::as_cpp<cpp11::decay_t<SEXP>>(dic), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(file_name)));
  END_CPP11
}
// red_execute.cpp
cpp11::writable::list redatam_query_filtered(SEXP dic, std::string spc, std::string filter_var, int filter_value);
extern "C" SEXP _censo2022arg_redatam_query_filtered(SEXP dic, SEXP spc, SEXP filter_var, SEXP filter_value) {
  BEGIN_CPP11
    return cpp11::as_sexp(redatam_query_filtered(cpp11::as_cpp<cpp11::decay_t<SEXP>>(dic), cpp11::as_cpp<cpp11::decay_t<std::string>>(spc), cpp11::as_cpp<cpp11::decay_t<std::string>>(filter_var), cpp11::as_cpp<cpp11::decay_t<int>>(filter_value)));
  END_CPP11
}
// red_initialize.cpp
std::string redatam_version();
extern "C" SEXP _censo2022arg_redatam_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(redatam_version());
  END_CPP11
}
// red_initialize.cpp
std::string redatam_info();
extern "C" SEXP _censo2022arg_redatam_info() {
  BEGIN_CPP11
    return cpp11::as_sexp(redatam_info());
  END_CPP11
}
// red_initialize.cpp
void redatam_init_(std::string packageDir);
extern "C" SEXP _censo2022arg_redatam_init_(SEXP packageDir) {
  BEGIN_CPP11
    redatam_init_(cpp11::as_cpp<cpp11::decay_t<std::string>>(packageDir));
    return R_NilValue;
  END_CPP11
}
// red_initialize.cpp
void redatam_destroy_();
extern "C" SEXP _censo2022arg_redatam_destroy_() {
  BEGIN_CPP11
    redatam_destroy_();
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_censo2022arg_redatam_destroy_",       (DL_FUNC) &_censo2022arg_redatam_destroy_,       0},
    {"_censo2022arg_redatam_info",           (DL_FUNC) &_censo2022arg_redatam_info,           0},
    {"_censo2022arg_redatam_init_",          (DL_FUNC) &_censo2022arg_redatam_init_,          1},
    {"_censo2022arg_redatam_internal_query", (DL_FUNC) &_censo2022arg_redatam_internal_query, 2},
    {"_censo2022arg_redatam_internal_run",   (DL_FUNC) &_censo2022arg_redatam_internal_run,   2},
    {"_censo2022arg_redatam_query_filtered", (DL_FUNC) &_censo2022arg_redatam_query_filtered, 4},
    {"_censo2022arg_redatam_version",        (DL_FUNC) &_censo2022arg_redatam_version,        0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_censo2022arg(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
