# Generated by cpp11: do not edit by hand

redatam_internal_query <- function(dic, spc) {
  .Call(`_censo2022arg_redatam_internal_query`, dic, spc)
}

redatam_internal_run <- function(dic, file_name) {
  .Call(`_censo2022arg_redatam_internal_run`, dic, file_name)
}

redatam_query_filtered <- function(dic, spc, filter_var, filter_value) {
  .Call(`_censo2022arg_redatam_query_filtered`, dic, spc, filter_var, filter_value)
}

redatam_version <- function() {
  .Call(`_censo2022arg_redatam_version`)
}

redatam_info <- function() {
  .Call(`_censo2022arg_redatam_info`)
}

redatam_init_ <- function(packageDir) {
  invisible(.Call(`_censo2022arg_redatam_init_`, packageDir))
}

redatam_destroy_ <- function() {
  invisible(.Call(`_censo2022arg_redatam_destroy_`))
}
